version: '3.1'

services:
  graphiql:
    #build: .
    image: graphiql:2.2.3
    command: gunicorn gpapi.wsgi -c gunicorn_config.py
    restart: unless-stopped
    container_name: graphiql
    volumes:
      # - ./app:/app
      - /docker_data/graphqlapi:/app
    ports:
      - "8086:8000"

  